version: '3'

services:
  # namenode节点
  namenode:
    build: .
    image: huldarchen/hadoop-hive:debian_x64
    ports:
      - 9870:9870
      - 8088:8088
      - 8983:8983
      - 9000:9000
    networks:
      - hadoop_hive
    volumes:
      - hadoop:/data/hadoop
    env_file:
      - ./hadoop.env
    environment:
      - HADOOP_MODE=namenode
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870 || curl -f http://localhost:8088 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  datanode:
    image: huldarchen/hadoop-hive:debian_x64
    networks:
      - hadoop_hive
    volumes:
      - hadoop:/data/hadoop
    env_file:
      - ./hadoop.env
    environment:
      - HADOOP_MODE=datanode
      - SERVICE_PRECONDITION=namenode:9870
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9864 || curl -f http://localhost:8042 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
  
  mysql8:
    build: ./mysql
    image: huldarchen/mysql-hive:8.0.33-debian
    networks:
      - hadoop_hive
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=Pwd@root830
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=Pwd@root830
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
      - --lower_case_table_names=1
    ports:
      - 3310:3306
    volumes:
      - hive_mysql8:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      interval: 15s
      retries: 10
    
  hive:
    image: huldarchen/hadoop-hive:debian_x64
    networks:
      - hadoop_hive
    env_file:
      - ./hadoop.env
    environment:
      - HADOOP_MODE=hive
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=Pwd@root830
      - SERVICE_PRECONDITION=namenode:9870 namenode:8088 datanode:9864 datanode:8042 mysql8:3306
    ports:
      - 10000:10000
      - 10002:10002
    volumes:
      - hadoop:/data/hadoop
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
  

networks:
  hadoop_hive:


volumes:
  hadoop:
  hive_mysql8: